### ISSUE TITLE
listar los forms en el template

### ISSUE THREAD

**Issue by johnnyvargast** [TimBest/django-multi-form-view#7]
Cuando listo el forms me trae los form existentes, pero cuando trato de acceder a los labels y errors del un form especifico no me funciona.

Deberia funcionar asi:
<pre>
{% for form in forms %}
     {% if form.errors %}
          {% for field in form %}
                {% for error in field.errors %}
                    {{ field.label }}
                    <strong>{{ error|escape }}</strong>
                {% endfor %}
          {% endfor %}
     {% endif %}
{% endfor %}
</pre>

Pero lo pruebo manualmente utilizando solo un form y si funciona :
<pre>
{% if forms.myform.errors %}
        {% for field in forms.myform %}
            {% for error in field.errors %}
                {{ field.label }} 
                <strong>{{ error|escape }}</strong>
            {% endfor %}
        {% endfor %}
{% endif %}
</pre>

**Comment by TimBest** [comment]
You should be able to get the desired effect by looping through the dictionary's values

```python
{% for form in forms.values() %}
     {% if form.errors %}
        ....
     {% endif %}
{% endfor %}
```
I made `forms` an dict so that you have context about what is rendering in the template and allowing for semantic access of the forms

forms as a dict (current implementation):
```
<form method="post">
  {% csrf_token %}
  {{ forms.form1.as_p }}
  {{ forms.contact_form.as_p }}
  <input type="submit" value="submit"/>
</form>
```

forms as a list (proposed implementation):
```
<form method="post">
  {% csrf_token %}
  {{ forms[0].as_p }}
  {{ forms[1].as_p }}
  <input type="submit" value="submit"/>
</form>
```

as a list you would have no idea what `forms[0]` is.
